"use client";

import { BarChart3, CalendarClock, CircleDollarSign, LoaderCircle, RefreshCw, ShieldAlert, Star, Users } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type CustomerMetric={customer_id:string;name:string;vehicle_count:number;work_order_count:number;lifetime_value:number;last_visit_at:string|null;outstanding_amount:number;average_rating:number};
type BranchKpi={active_customers:number;open_orders:number;month_revenue:number;month_cash:number;average_rating:number;open_warranty_claims:number};
type Month={period_month:string;delivered_orders:number;revenue:number;cost:number};

export function CrmDashboard(){
 const[rows,setRows]=useState<CustomerMetric[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id||!p.last_branch_id)throw new Error("Conclua o onboarding.");const{data,error:e}=await s.from("crm_customer_overview").select("*").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).order("lifetime_value",{ascending:false}).limit(100);if(e)throw e;setRows((data??[])as CustomerMetric[])}catch(c){setError(c instanceof Error?c.message:"Não foi possível carregar o CRM.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const metrics=useMemo(()=>{const newestVisit=Math.max(0,...rows.map(r=>r.last_visit_at?new Date(r.last_visit_at).getTime():0));const inactiveCutoff=newestVisit-180*86400000;return{active:rows.length,recurring:rows.filter(r=>Number(r.work_order_count)>=3).length,inactive:rows.filter(r=>!r.last_visit_at||new Date(r.last_visit_at).getTime()<inactiveCutoff).length,delinquent:rows.filter(r=>Number(r.outstanding_amount)>0).length,rating:rows.length?rows.reduce((s,r)=>s+Number(r.average_rating),0)/rows.length:0}},[rows]);
 return <main className="mx-auto max-w-[1520px] px-4 py-5 lg:px-7 lg:py-6"><Header title="CRM de clientes" subtitle="Recorrência, inatividade, inadimplência e valor do relacionamento em uma única visão." onRefresh={load}/>{error&&<Alert>{error}</Alert>}
 <section className="grid gap-px border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Users} label="Clientes ativos" value={String(metrics.active)}/><Metric icon={Star} label="Recorrentes" value={String(metrics.recurring)}/><Metric icon={CalendarClock} label="Inativos há 180 dias" value={String(metrics.inactive)}/><Metric icon={ShieldAlert} label="Com débitos" value={String(metrics.delinquent)} danger/><Metric icon={Star} label="Avaliação média" value={metrics.rating?metrics.rating.toFixed(1):"—"}/></section>
 <div className="mt-5 flex flex-wrap gap-2"><Link href="/clientes" className="h-9 bg-[var(--brand)] px-4 py-2 text-xs font-bold text-white">Gerenciar clientes</Link><Link href="/segmentos" className="h-9 border border-[var(--line-strong)] px-4 py-2 text-xs font-bold">Segmentos</Link><Link href="/automacoes" className="h-9 border border-[var(--line-strong)] px-4 py-2 text-xs font-bold">Pós-venda</Link></div>
 <section className="mt-5 border border-[var(--line)] bg-[var(--surface)]"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-bold">Relacionamento por cliente</h2><p className="mt-1 text-xs text-[var(--ink-muted)]">Ordenado pelo valor histórico de ordens entregues.</p></div>{loading?<Loading/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-[var(--surface-muted)]"><tr><Th>Cliente</Th><Th>Veículos</Th><Th>Ordens</Th><Th>Última visita</Th><Th>Valor histórico</Th><Th>Em aberto</Th></tr></thead><tbody className="divide-y divide-[var(--line)]">{rows.map(r=><tr key={r.customer_id}><Td strong>{r.name}</Td><Td>{r.vehicle_count}</Td><Td>{r.work_order_count}</Td><Td>{r.last_visit_at?date(r.last_visit_at):"Sem visita"}</Td><Td>{money(r.lifetime_value)}</Td><Td danger={Number(r.outstanding_amount)>0}>{money(r.outstanding_amount)}</Td></tr>)}</tbody></table></div>}</section></main>;
}

export function BiDashboard(){
 const[kpi,setKpi]=useState<BranchKpi|null>(null);const[months,setMonths]=useState<Month[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id||!p.last_branch_id)throw new Error("Conclua o onboarding.");const[a,b]=await Promise.all([s.from("bi_branch_overview").select("*").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).single(),s.from("bi_monthly_performance").select("*").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).order("period_month",{ascending:false}).limit(12)]);if(a.error||b.error)throw a.error??b.error;setKpi(a.data as BranchKpi);setMonths(((b.data??[])as Month[]).reverse())}catch(c){setError(c instanceof Error?c.message:"Não foi possível carregar os indicadores.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);const max=Math.max(1,...months.map(m=>Number(m.revenue)));
 return <main className="mx-auto max-w-[1520px] px-4 py-5 lg:px-7 lg:py-6"><Header title="BI da oficina" subtitle="Indicadores operacionais, financeiros, satisfação e garantia por filial." onRefresh={load}/>{error&&<Alert>{error}</Alert>}
 <section className="grid gap-px border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2 xl:grid-cols-6"><Metric icon={Users} label="Clientes" value={String(kpi?.active_customers??"—")}/><Metric icon={BarChart3} label="OS em aberto" value={String(kpi?.open_orders??"—")}/><Metric icon={CircleDollarSign} label="Receita do mês" value={money(kpi?.month_revenue)}/><Metric icon={CircleDollarSign} label="Caixa do mês" value={money(kpi?.month_cash)}/><Metric icon={Star} label="Avaliação" value={kpi?Number(kpi.average_rating).toFixed(1):"—"}/><Metric icon={ShieldAlert} label="Garantias abertas" value={String(kpi?.open_warranty_claims??"—")} danger={Boolean(kpi?.open_warranty_claims)}/></section>
 <section className="mt-5 border border-[var(--line)] bg-[var(--surface)]"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-bold">Receita e custo por mês</h2><p className="mt-1 text-xs text-[var(--ink-muted)]">Somente ordens de serviço entregues.</p></div>{loading?<Loading/>:<div className="flex h-72 items-end gap-3 overflow-x-auto p-5">{months.length?months.map(m=><div key={m.period_month} className="flex min-w-16 flex-1 flex-col items-center justify-end"><div className="flex h-52 items-end gap-1"><div className="w-5 bg-[var(--brand)]" style={{height:`${Math.max(3,Number(m.revenue)/max*200)}px`}} title={`Receita ${money(m.revenue)}`}/><div className="w-5 bg-[#d0685b]" style={{height:`${Math.max(3,Number(m.cost)/max*200)}px`}} title={`Custo ${money(m.cost)}`}/></div><span className="mt-2 text-[10px] font-semibold text-[var(--ink-muted)]">{month(m.period_month)}</span></div>):<p className="m-auto text-xs text-[var(--ink-muted)]">Ainda não há ordens entregues para compor o histórico.</p>}</div>}</section></main>;
}

function Header({title,subtitle,onRefresh}:{title:string;subtitle:string;onRefresh:()=>Promise<void>}){return <div className="mb-5 flex items-start justify-between gap-4"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--brand)]">Fase 5 • Recursos avançados</p><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">{subtitle}</p></div><button onClick={()=>void onRefresh()} className="grid size-10 place-items-center border border-[var(--line)]" aria-label="Atualizar"><RefreshCw size={16}/></button></div>}
function Metric({icon:Icon,label,value,danger}:{icon:typeof Users;label:string;value:string;danger?:boolean}){return <article className="bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[var(--ink-muted)]">{label}</p><Icon size={17} className={danger?"text-[var(--danger)]":"text-[var(--brand)]"}/></div><p className={`mt-3 text-2xl font-bold ${danger?"text-[var(--danger)]":""}`}>{value}</p></article>}
function Alert({children}:{children:string}){return <div className="mb-4 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{children}</div>}
function Loading(){return <div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>}
function Th({children}:{children:string}){return <th className="px-4 py-3 font-bold">{children}</th>}
function Td({children,strong,danger}:{children:React.ReactNode;strong?:boolean;danger?:boolean}){return <td className={`px-4 py-3 ${strong?"font-bold":""} ${danger?"text-[var(--danger)]":""}`}>{children}</td>}
const money=(v?:number|null)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const date=(v:string)=>new Intl.DateTimeFormat("pt-BR").format(new Date(v));
const month=(v:string)=>new Intl.DateTimeFormat("pt-BR",{month:"short",year:"2-digit"}).format(new Date(`${v}T12:00:00`));
