"use client";

import { LoaderCircle, RefreshCw, Search } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Audit={id:number;occurred_at:string;entity_table:string;entity_id:string|null;action:string;actor_id:string|null};
const PAGE_SIZE=50;
export function AuditModule(){
 const[rows,setRows]=useState<Audit[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[page,setPage]=useState(0);const[table,setTable]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id)throw new Error("Selecione uma empresa.");let q=s.from("audit_logs").select("id,occurred_at,entity_table,entity_id,action,actor_id").eq("organization_id",p.last_organization_id).order("occurred_at",{ascending:false}).range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE-1);if(table.trim())q=q.ilike("entity_table",`%${table.trim().replace(/[%_,()]/g,"")}%`);const{data,error:e}=await q;if(e)throw e;setRows((data??[])as Audit[])}catch(c){setError(c instanceof Error?c.message:"Não foi possível consultar a auditoria.")}finally{setLoading(false)}},[page,table]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const search=(event:FormEvent)=>{event.preventDefault();setPage(0);void load()};
 return <main className="mx-auto max-w-[1200px] px-4 py-5 lg:px-7 lg:py-6"><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--brand)]">Governança</p><h1 className="text-2xl font-bold">Auditoria</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">Histórico imutável das ações críticas da empresa.</p></div><form onSubmit={search} className="flex"><label className="sr-only" htmlFor="audit-table">Filtrar entidade</label><input id="audit-table" value={table} onChange={e=>setTable(e.target.value)} className="field w-56" placeholder="Tabela ou módulo"/><button className="grid size-10 place-items-center bg-[var(--brand)] text-white" aria-label="Pesquisar"><Search size={16}/></button><button type="button" onClick={()=>void load()} className="ml-2 grid size-10 place-items-center border border-[var(--line)]" aria-label="Atualizar"><RefreshCw size={16}/></button></form></div>{error&&<div className="mb-4 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{error}</div>}<section className="overflow-x-auto border border-[var(--line)] bg-[var(--surface)]">{loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>:<table className="w-full min-w-[760px] text-left text-xs"><thead className="sticky top-0 bg-[var(--surface-muted)] text-[10px] uppercase tracking-[.08em] text-[var(--ink-muted)]"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Ação</th><th className="px-4 py-3">Entidade</th><th className="px-4 py-3">Registro</th><th className="px-4 py-3">Responsável</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id} className="border-t border-[var(--line)]"><td className="whitespace-nowrap px-4 py-3">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(row.occurred_at))}</td><td className="px-4 py-3 font-bold uppercase">{row.action}</td><td className="px-4 py-3">{row.entity_table}</td><td className="max-w-52 truncate px-4 py-3 font-mono text-[10px]">{row.entity_id??"—"}</td><td className="px-4 py-3 font-mono text-[10px]">{row.actor_id?.slice(0,8)??"Sistema"}</td></tr>):<tr><td colSpan={5} className="p-12 text-center text-[var(--ink-muted)]">Nenhum evento encontrado.</td></tr>}</tbody></table>}</section><div className="mt-4 flex justify-end gap-2"><button disabled={page===0} onClick={()=>setPage(value=>Math.max(0,value-1))} className="h-9 border border-[var(--line)] px-4 text-xs font-bold disabled:opacity-40">Anterior</button><span className="grid h-9 min-w-9 place-items-center bg-[var(--surface-muted)] text-xs font-bold">{page+1}</span><button disabled={rows.length<PAGE_SIZE} onClick={()=>setPage(value=>value+1)} className="h-9 border border-[var(--line)] px-4 text-xs font-bold disabled:opacity-40">Próxima</button></div></main>;
}
