"use client";

import { CheckCircle2, ClipboardCheck, LoaderCircle, ShieldCheck, Star, Wrench, XCircle } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Vehicle={id:string;plate:string;brand:string;model:string;mileage:number};type Order={id:string;number:string;status:string;complaint:string;entry_at:string;due_at:string|null;total:number;vehicle_id:string};type Item={id:string;description:string;quantity:number;total:number;approval_status:string};type Estimate={id:string;number:string;status:string;valid_until:string|null;total:number;items:Item[]};type Warranty={id:string;description:string;type:string;starts_at:string;expires_at:string;status:string};type Snapshot={customer:{name:string};expires_at:string;vehicles:Vehicle[];work_orders:Order[];estimates:Estimate[];warranties:Warranty[]};

export function CustomerPortal(){
 const[token,setToken]=useState("");const[data,setData]=useState<Snapshot|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[action,setAction]=useState(false);const[rating,setRating]=useState(0);const[comment,setComment]=useState("");
 const load=useCallback(async(raw?:string)=>{const value=raw??token;if(!value){setLoading(false);return}setLoading(true);setError(null);try{const s=createClient();const{data:result,error:e}=await s.rpc("get_customer_portal",{p_token:value});if(e)throw e;setData(result as Snapshot);setToken(value)}catch{setData(null);setError("Este acesso é inválido, expirou ou foi revogado.")}finally{setLoading(false)}},[token]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const params=new URLSearchParams(window.location.hash.slice(1));const raw=params.get("token")??"";if(raw)void load(raw);else setLoading(false)},0);return()=>window.clearTimeout(timer)},[load]);
 const decide=async(estimate:Estimate,decision:"approved"|"rejected")=>{if(!window.confirm(decision==="approved"?"Aprovar todos os itens deste orçamento?":"Recusar todos os itens deste orçamento?"))return;setAction(true);setError(null);const s=createClient();const{error:e}=await s.rpc("portal_respond_estimate",{p_token:token,p_estimate_id:estimate.id,p_decision:decision,p_notes:null});if(e)setError(e.message);else await load();setAction(false)};
 const sendRating=async(orderId:string)=>{setAction(true);setError(null);const s=createClient();const{error:e}=await s.rpc("portal_submit_rating",{p_token:token,p_work_order_id:orderId,p_rating:rating,p_comment:comment||null});if(e)setError(e.message);else{setComment("");window.alert("Avaliação enviada. Obrigado!")}setAction(false)};
 if(loading)return <PortalFrame><div className="grid min-h-[70vh] place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div></PortalFrame>;
 if(!data)return <PortalFrame><section className="mx-auto mt-16 max-w-md border border-[var(--line)] bg-white p-6 text-center"><ShieldCheck className="mx-auto text-[var(--brand)]"/><h1 className="mt-4 text-xl font-bold">Acessar portal</h1><p className="mt-2 text-sm text-[var(--ink-muted)]">Cole o token recebido pela oficina.</p>{error&&<p className="mt-4 text-xs text-[var(--danger)]">{error}</p>}<input value={token} onChange={e=>setToken(e.target.value.trim())} className="mt-5 h-10 w-full border border-[var(--line-strong)] px-3 text-sm" placeholder="Token de acesso"/><button onClick={()=>void load()} className="mt-3 h-10 w-full bg-[var(--brand)] text-sm font-bold text-white">Entrar com segurança</button></section></PortalFrame>;
 return <PortalFrame><main className="mx-auto max-w-6xl px-4 py-7"><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--brand)]">Portal do cliente</p><h1 className="mt-1 text-2xl font-bold">Olá, {data.customer.name}</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">Acompanhe serviços, orçamentos e garantias. Acesso válido até {dateTime(data.expires_at)}.</p>{error&&<div className="mt-5 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{error}</div>}
 <section className="mt-6 grid gap-4 md:grid-cols-3">{data.vehicles.map(v=><article key={v.id} className="border border-[var(--line)] bg-white p-5"><Wrench size={18} className="text-[var(--brand)]"/><p className="mt-3 text-lg font-bold">{v.plate}</p><p className="text-sm text-[var(--ink-muted)]">{v.brand} {v.model}</p><p className="mt-3 text-xs">{Number(v.mileage).toLocaleString("pt-BR")} km</p></article>)}</section>
 <Section title="Ordens de serviço" icon={Wrench}>{data.work_orders.length?data.work_orders.map(o=><article key={o.id} className="border-b border-[var(--line)] p-5 last:border-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">OS {o.number}</p><p className="mt-1 text-xs text-[var(--ink-muted)]">{o.complaint}</p></div><Status value={o.status}/></div><div className="mt-4 grid gap-2 text-xs sm:grid-cols-3"><span>Entrada: {date(o.entry_at)}</span><span>Previsão: {o.due_at?date(o.due_at):"A definir"}</span><strong>{money(o.total)}</strong></div>{o.status==="delivered"&&<div className="mt-4 border-t border-[var(--line)] pt-4"><p className="text-xs font-bold">Avalie o atendimento</p><div className="mt-2 flex gap-1">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} aria-label={`${n} estrelas`}><Star size={20} className={n<=rating?"fill-[#d69b20] text-[#d69b20]":"text-[var(--line-strong)]"}/></button>)}</div>{rating>0&&<div className="mt-3 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} className="h-9 min-w-0 flex-1 border border-[var(--line)] px-3 text-xs" placeholder="Comentário opcional"/><button disabled={action} onClick={()=>void sendRating(o.id)} className="bg-[var(--brand)] px-4 text-xs font-bold text-white">Enviar</button></div>}</div>}</article>):<Empty/>}</Section>
 <Section title="Orçamentos" icon={ClipboardCheck}>{data.estimates.length?data.estimates.map(e=><article key={e.id} className="border-b border-[var(--line)] p-5 last:border-0"><div className="flex items-center justify-between"><div><p className="font-bold">Orçamento {e.number}</p><p className="mt-1 text-xs text-[var(--ink-muted)]">Validade: {e.valid_until?date(e.valid_until):"não informada"}</p></div><strong>{money(e.total)}</strong></div><div className="mt-4 divide-y divide-[var(--line)] border-y border-[var(--line)]">{e.items.map(i=><div key={i.id} className="flex items-center justify-between gap-4 py-2 text-xs"><span>{i.description} × {i.quantity}</span><span>{money(i.total)}</span></div>)}</div>{["sent","viewed","partially_approved"].includes(e.status)?<div className="mt-4 flex flex-wrap gap-2"><button disabled={action} onClick={()=>void decide(e,"approved")} className="inline-flex h-9 items-center gap-2 bg-[var(--brand)] px-4 text-xs font-bold text-white"><CheckCircle2 size={15}/>Aprovar itens</button><button disabled={action} onClick={()=>void decide(e,"rejected")} className="inline-flex h-9 items-center gap-2 border border-[var(--line-strong)] px-4 text-xs font-bold text-[var(--danger)]"><XCircle size={15}/>Recusar</button></div>:<div className="mt-4"><Status value={e.status}/></div>}</article>):<Empty/>}</Section>
 <Section title="Garantias" icon={ShieldCheck}>{data.warranties.length?data.warranties.map(g=><article key={g.id} className="flex items-center gap-4 border-b border-[var(--line)] p-5 last:border-0"><div className="grid size-9 place-items-center bg-[var(--brand-soft)] text-[var(--brand)]"><ShieldCheck size={17}/></div><div className="min-w-0 flex-1"><p className="font-bold">{g.description}</p><p className="mt-1 text-xs text-[var(--ink-muted)]">Válida até {date(g.expires_at)}</p></div><Status value={g.status}/></article>):<Empty/>}</Section></main></PortalFrame>;
}
function PortalFrame({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-[var(--canvas)] text-[var(--ink)]"><header className="border-b border-[var(--line)] bg-[var(--sidebar)] px-5 py-4 text-white"><div className="mx-auto flex max-w-6xl items-center gap-3"><div className="grid size-9 place-items-center bg-[var(--brand)]"><Wrench size={18}/></div><div><p className="font-bold">MOTORA</p><p className="text-[10px] uppercase tracking-[.16em] text-white/60">Portal seguro</p></div></div></header>{children}</div>}
function Section({title,icon:Icon,children}:{title:string;icon:typeof Wrench;children:React.ReactNode}){return <section className="mt-6 border border-[var(--line)] bg-white"><div className="flex items-center gap-2 border-b border-[var(--line)] px-5 py-4"><Icon size={17} className="text-[var(--brand)]"/><h2 className="font-bold">{title}</h2></div>{children}</section>}
function Status({value}:{value:string}){return <span className="rounded-full bg-[var(--brand-soft)] px-2.5 py-1 text-[10px] font-bold text-[var(--brand)]">{value.replaceAll("_"," ")}</span>}
function Empty(){return <p className="p-6 text-center text-xs text-[var(--ink-muted)]">Nenhum registro disponível neste acesso.</p>}
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);const date=(v:string)=>new Intl.DateTimeFormat("pt-BR").format(new Date(v));const dateTime=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));
