"use client";

import { Bell, CheckCheck, LoaderCircle, RefreshCw, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Notification = { id:string; severity:string; title:string; message:string; href:string|null; read_at:string|null; created_at:string };

function useNotifications(limit=50){
  const [items,setItems]=useState<Notification[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id||!p.last_branch_id)throw new Error("Selecione uma filial.");const refreshed=await s.rpc("refresh_operational_notifications",{p_branch_id:p.last_branch_id});if(refreshed.error)throw refreshed.error;const{data,error:e}=await s.from("notifications").select("id,severity,title,message,href,read_at,created_at").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).order("created_at",{ascending:false}).limit(limit);if(e)throw e;setItems((data??[])as Notification[])}catch(c){setError(c instanceof Error?c.message:"Não foi possível carregar as notificações.")}finally{setLoading(false)}},[limit]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const read=async(id?:string)=>{const s=createClient();let q=s.from("notifications").update({read_at:new Date().toISOString()}).is("read_at",null);if(id)q=q.eq("id",id);const{error:e}=await q;if(e)setError(e.message);else setItems(current=>current.map(item=>!id||item.id===id?{...item,read_at:item.read_at??new Date().toISOString()}:item))};
  return{items,loading,error,load,read};
}

const tone=(severity:string)=>severity==="critical"?"bg-[#fff0ee] text-[var(--danger)]":severity==="warning"?"bg-[#fff8df] text-[#7b5a00]":"bg-[var(--brand-soft)] text-[var(--brand)]";
const format=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));

export function NotificationCenter(){
  const[open,setOpen]=useState(false);const{items,loading,error,load,read}=useNotifications(20);const unread=items.filter(item=>!item.read_at).length;
  return <div className="relative"><button onClick={()=>setOpen(value=>!value)} className="relative grid size-9 place-items-center text-[var(--ink-muted)]" aria-label={`Notificações${unread?` (${unread} não lidas)`:""}`} aria-expanded={open}><Bell size={18}/>{unread>0&&<span className="absolute right-1 top-1 grid min-w-4 place-items-center rounded-full bg-[var(--danger)] px-1 text-[9px] font-bold text-white">{Math.min(unread,99)}</span>}</button>{open&&<div className="fixed inset-x-3 top-16 z-50 max-h-[70vh] overflow-hidden border border-[var(--line)] bg-[var(--surface)] shadow-2xl sm:absolute sm:inset-auto sm:right-0 sm:top-11 sm:w-[390px]"><div className="flex items-center gap-2 border-b border-[var(--line)] px-4 py-3"><div className="flex-1"><p className="text-sm font-bold">Notificações</p><p className="text-[11px] text-[var(--ink-muted)]">{unread} não lida{unread===1?"":"s"}</p></div><button onClick={()=>void read()} className="p-2 text-[var(--brand)]" aria-label="Marcar todas como lidas"><CheckCheck size={17}/></button><button onClick={()=>setOpen(false)} className="p-2" aria-label="Fechar"><X size={17}/></button></div><div className="max-h-[52vh] overflow-y-auto">{loading?<div className="grid h-40 place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>:error?<p className="p-5 text-xs text-[var(--danger)]">{error}</p>:items.length?items.map(item=><Link key={item.id} href={item.href??"/notificacoes"} onClick={()=>{void read(item.id);setOpen(false)}} className={`flex gap-3 border-b border-[var(--line)] p-4 ${item.read_at?"opacity-65":"bg-[var(--surface-muted)]"}`}><span className={`mt-0.5 size-2 shrink-0 rounded-full ${tone(item.severity)}`}/><span className="min-w-0"><span className="block text-xs font-bold">{item.title}</span><span className="mt-1 block text-[11px] text-[var(--ink-muted)]">{item.message}</span><span className="mt-1.5 block text-[10px] text-[var(--ink-muted)]">{format(item.created_at)}</span></span></Link>):<p className="p-8 text-center text-xs text-[var(--ink-muted)]">Nenhum alerta operacional.</p>}</div><div className="flex border-t border-[var(--line)]"><button onClick={()=>void load()} className="inline-flex h-10 flex-1 items-center justify-center gap-2 text-xs font-bold"><RefreshCw size={13}/>Atualizar</button><Link href="/notificacoes" onClick={()=>setOpen(false)} className="inline-flex h-10 flex-1 items-center justify-center border-l border-[var(--line)] text-xs font-bold text-[var(--brand)]">Ver central</Link></div></div>}</div>;
}

export function NotificationsModule(){
  const{items,loading,error,load,read}=useNotifications(100);return <main className="mx-auto max-w-[1000px] px-4 py-5 lg:px-7 lg:py-6"><div className="mb-5 flex items-start justify-between"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--brand)]">Fase 5 • Operação assistida</p><h1 className="text-2xl font-bold">Central de notificações</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">Orçamentos pendentes, garantias próximas e recebimentos vencidos.</p></div><div className="flex gap-2"><button onClick={()=>void read()} className="inline-flex h-10 items-center gap-2 border border-[var(--line)] px-3 text-xs font-bold"><CheckCheck size={15}/>Ler todas</button><button onClick={()=>void load()} className="grid size-10 place-items-center border border-[var(--line)]" aria-label="Atualizar"><RefreshCw size={16}/></button></div></div>{error&&<div className="mb-4 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{error}</div>}{loading?<div className="grid min-h-72 place-items-center border border-[var(--line)] bg-[var(--surface)]"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>:<section className="border border-[var(--line)] bg-[var(--surface)]">{items.length?items.map(item=><article key={item.id} className={`flex gap-4 border-b border-[var(--line)] p-5 last:border-0 ${item.read_at?"opacity-65":""}`}><span className={`mt-1 size-3 shrink-0 rounded-full ${tone(item.severity)}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold">{item.title}</h2>{!item.read_at&&<span className="bg-[var(--brand-soft)] px-2 py-0.5 text-[10px] font-bold text-[var(--brand)]">Nova</span>}</div><p className="mt-1 text-xs text-[var(--ink-muted)]">{item.message}</p><p className="mt-2 text-[10px] text-[var(--ink-muted)]">{format(item.created_at)}</p></div><div className="flex items-center gap-2">{!item.read_at&&<button onClick={()=>void read(item.id)} className="p-2 text-[var(--brand)]" aria-label="Marcar como lida"><CheckCheck size={16}/></button>}{item.href&&<Link href={item.href} className="border border-[var(--line)] px-3 py-2 text-xs font-bold">Abrir</Link>}</div></article>):<p className="p-12 text-center text-sm text-[var(--ink-muted)]">Tudo certo por aqui.</p>}</section>}</main>;
}
