"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { createClient } from "@/lib/supabase/client";

const schema=z.object({password:z.string().min(8,"Use ao menos 8 caracteres."),confirmation:z.string()}).refine(value=>value.password===value.confirmation,{path:["confirmation"],message:"As senhas não coincidem."});type Values=z.infer<typeof schema>;
export function PasswordResetForm(){const[ready,setReady]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const{register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema)});const prepare=useCallback(async()=>{try{const s=createClient();const code=new URLSearchParams(window.location.search).get("code");if(code){const{error:e}=await s.auth.exchangeCodeForSession(code);if(e)throw e;window.history.replaceState({},"","/login?mode=reset")}const{data:{session}}=await s.auth.getSession();if(!session)throw new Error("invalid_session");setReady(true)}catch{setError("O link é inválido ou expirou. Solicite uma nova recuperação.")}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void prepare(),0);return()=>window.clearTimeout(timer)},[prepare]);const submit=async(values:Values)=>{setError(null);try{const{error:e}=await createClient().auth.updateUser({password:values.password});if(e)throw e;setMessage("Senha atualizada. Você já pode entrar com a nova senha.")}catch{setError("Não foi possível atualizar a senha.")}};if(!ready&&!error)return <div className="mt-10 grid place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>;return <form onSubmit={handleSubmit(submit)} className="mt-8 space-y-5" noValidate>{!message&&<><div><label htmlFor="new-password" className="mb-2 block text-xs font-bold">Nova senha</label><input id="new-password" type="password" autoComplete="new-password" className="field w-full" {...register("password")}/>{errors.password&&<p className="mt-1.5 text-xs text-[var(--danger)]">{errors.password.message}</p>}</div><div><label htmlFor="confirm-password" className="mb-2 block text-xs font-bold">Confirme a senha</label><input id="confirm-password" type="password" autoComplete="new-password" className="field w-full" {...register("confirmation")}/>{errors.confirmation&&<p className="mt-1.5 text-xs text-[var(--danger)]">{errors.confirmation.message}</p>}</div></>}{error&&<div role="alert" className="border border-[#f0b4ae] bg-[#fff2f0] px-3 py-2.5 text-xs text-[var(--danger)]">{error}</div>}{message&&<div role="status" className="border border-[#aad8cf] bg-[var(--brand-soft)] px-3 py-2.5 text-xs text-[var(--brand)]">{message}</div>}{ready&&!message&&<button disabled={isSubmitting} className="flex h-11 w-full items-center justify-center gap-2 bg-[var(--brand)] font-bold text-white disabled:opacity-60">{isSubmitting&&<LoaderCircle size={17} className="animate-spin"/>}Salvar nova senha</button>}<Link href="/login" className="block text-center text-xs font-bold text-[var(--brand)]">Ir para o login</Link></form>}
