"use client";

import { Check, Copy, ExternalLink, KeyRound, LoaderCircle, RefreshCw, ShieldOff } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Customer={id:string;name:string;primary_phone:string|null};type Order={id:string;customer_id:string;number:string;status:string};type Access={id:string;customer_id:string;work_order_id:string|null;expires_at:string;revoked_at:string|null;last_used_at:string|null;created_at:string};

export function PortalAccessManager(){
 const[customers,setCustomers]=useState<Customer[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[accesses,setAccesses]=useState<Access[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[link,setLink]=useState("");const[copied,setCopied]=useState(false);const[form,setForm]=useState({customer_id:"",work_order_id:"",hours:"72"});
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id||!p.last_branch_id)throw new Error("Conclua o onboarding.");const[c,o,a,cfg]=await Promise.all([s.from("customers").select("id,name,primary_phone").eq("organization_id",p.last_organization_id).eq("primary_branch_id",p.last_branch_id).is("deleted_at",null).order("name").limit(500),s.from("work_orders").select("id,customer_id,number,status").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).is("deleted_at",null).order("entry_at",{ascending:false}).limit(300),s.from("portal_access_tokens").select("id,customer_id,work_order_id,expires_at,revoked_at,last_used_at,created_at").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).order("created_at",{ascending:false}).limit(100),s.from("application_settings").select("value").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).eq("key","portal_token_hours").maybeSingle()]);const first=c.error??o.error??a.error??cfg.error;if(first)throw first;setCustomers((c.data??[])as Customer[]);setOrders((o.data??[])as Order[]);setAccesses((a.data??[])as Access[]);const configured=(cfg.data?.value as {value?:unknown}|undefined)?.value;if(configured)setForm(current=>({...current,hours:String(configured)}))}catch(c){setError(c instanceof Error?c.message:"Não foi possível carregar os acessos.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);const customerMap=useMemo(()=>Object.fromEntries(customers.map(c=>[c.id,c.name])),[customers]);const filteredOrders=orders.filter(o=>o.customer_id===form.customer_id);
 const issue=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError(null);setLink("");try{const s=createClient();const{data,error:rpcError}=await s.rpc("create_portal_access",{p_customer_id:form.customer_id,p_work_order_id:form.work_order_id||null,p_hours:Number(form.hours)});if(rpcError)throw rpcError;const token=String(data);setLink(`${window.location.origin}/portal#token=${token}`);await load()}catch(c){setError(c instanceof Error?c.message:"Não foi possível emitir o acesso.")}finally{setSaving(false)}};
 const revoke=async(id:string)=>{if(!window.confirm("Revogar este acesso imediatamente?"))return;const s=createClient();const{error:e}=await s.from("portal_access_tokens").update({revoked_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else await load()};
 const copy=async()=>{await navigator.clipboard.writeText(link);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};
 return <main className="mx-auto max-w-[1200px] px-4 py-5 lg:px-7 lg:py-6"><div className="mb-5 flex items-start justify-between"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--brand)]">Portal do cliente</p><h1 className="text-2xl font-bold">Acessos temporários</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">Crie links seguros, com prazo de validade e acesso apenas ao serviço escolhido.</p></div><button onClick={()=>void load()} className="grid size-10 place-items-center border border-[var(--line)]"><RefreshCw size={16}/></button></div>{error&&<div className="mb-4 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{error}</div>}
 <section className="grid gap-5 lg:grid-cols-[420px_1fr]"><form onSubmit={issue} className="border border-[var(--line)] bg-[var(--surface)] p-5"><div className="grid size-10 place-items-center bg-[var(--brand-soft)] text-[var(--brand)]"><KeyRound size={19}/></div><h2 className="mt-4 font-bold">Novo acesso</h2><label className="mt-4 block text-xs font-bold">Cliente<select required value={form.customer_id} onChange={e=>setForm({customer_id:e.target.value,work_order_id:"",hours:form.hours})} className="mt-2 h-10 w-full border border-[var(--line-strong)] px-3"><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="mt-4 block text-xs font-bold">Ordem de serviço (opcional)<select value={form.work_order_id} onChange={e=>setForm({...form,work_order_id:e.target.value})} className="mt-2 h-10 w-full border border-[var(--line-strong)] px-3"><option value="">Todo o histórico permitido</option>{filteredOrders.map(o=><option key={o.id} value={o.id}>OS {o.number} • {o.status.replaceAll("_"," ")}</option>)}</select></label><label className="mt-4 block text-xs font-bold">Validade em horas<input required min="1" max="720" type="number" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})} className="mt-2 h-10 w-full border border-[var(--line-strong)] px-3"/></label><button disabled={saving||!form.customer_id} className="mt-5 inline-flex h-10 w-full items-center justify-center gap-2 bg-[var(--brand)] text-sm font-bold text-white disabled:opacity-50">{saving&&<LoaderCircle size={15} className="animate-spin"/>}Emitir link seguro</button>{link&&<div className="mt-5 border border-[#a9d8cf] bg-[var(--brand-soft)] p-3"><p className="text-xs font-bold text-[var(--brand)]">Link emitido — copie agora</p><p className="mt-2 break-all text-[11px] text-[var(--ink-muted)]">{link}</p><div className="mt-3 flex gap-2"><button type="button" onClick={()=>void copy()} className="inline-flex h-9 items-center gap-2 bg-[var(--brand)] px-3 text-xs font-bold text-white">{copied?<Check size={14}/>:<Copy size={14}/>}Copiar</button><a href={link} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-2 border border-[var(--line-strong)] px-3 text-xs font-bold"><ExternalLink size={14}/>Abrir</a></div></div>}</form>
 <section className="border border-[var(--line)] bg-[var(--surface)]"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-bold">Histórico de acessos</h2><p className="mt-1 text-xs text-[var(--ink-muted)]">O token bruto nunca é armazenado e não pode ser recuperado depois.</p></div>{loading?<div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>:<div className="divide-y divide-[var(--line)]">{accesses.length?accesses.map(a=>{const expired=new Date(a.expires_at)<=new Date();const active=!a.revoked_at&&!expired;return <article key={a.id} className="flex items-center gap-4 px-5 py-4"><div className={`grid size-9 place-items-center ${active?"bg-[var(--brand-soft)] text-[var(--brand)]":"bg-[var(--surface-muted)] text-[var(--ink-muted)]"}`}><KeyRound size={16}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{customerMap[a.customer_id]??"Cliente"}</p><p className="mt-1 text-[11px] text-[var(--ink-muted)]">{active?`Válido até ${format(a.expires_at)}`:a.revoked_at?"Revogado":"Expirado"}{a.last_used_at?` • usado em ${format(a.last_used_at)}`:" • ainda não utilizado"}</p></div>{active&&<button onClick={()=>void revoke(a.id)} className="inline-flex h-9 items-center gap-2 border border-[var(--line)] px-3 text-xs font-bold text-[var(--danger)]"><ShieldOff size={14}/>Revogar</button>}</article>}):<p className="p-8 text-center text-xs text-[var(--ink-muted)]">Nenhum acesso emitido.</p>}</div>}</section></section></main>;
}
const format=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));
