"use client";

import { LoaderCircle, Save } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Values={allowNegative:boolean;stockEvent:string;warrantyDays:string;portalHours:string;discountLimit:string};
const defaults:Values={allowNegative:false,stockEvent:"work_order_finish",warrantyDays:"90",portalHours:"72",discountLimit:"10"};
export function SettingsModule(){
 const[values,setValues]=useState(defaults);const[context,setContext]=useState<{org:string;branch:string;user:string}|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id||!p.last_branch_id)throw new Error("Selecione uma filial.");setContext({org:p.last_organization_id,branch:p.last_branch_id,user:user.id});const{data,error:e}=await s.from("application_settings").select("key,value").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).in("key",["allow_negative_stock","stock_issue_event","default_warranty_days","portal_token_hours","high_discount_limit"]);if(e)throw e;const map=Object.fromEntries((data??[]).map(row=>[row.key,(row.value as {value?:unknown})?.value]));setValues({allowNegative:Boolean(map.allow_negative_stock??false),stockEvent:String(map.stock_issue_event??"work_order_finish"),warrantyDays:String(map.default_warranty_days??90),portalHours:String(map.portal_token_hours??72),discountLimit:String(map.high_discount_limit??10)})}catch(c){setError(c instanceof Error?c.message:"Não foi possível carregar as configurações.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!context)return;setSaving(true);setError(null);setMessage(null);try{const rows=[['allow_negative_stock',values.allowNegative],['stock_issue_event',values.stockEvent],['default_warranty_days',Number(values.warrantyDays)],['portal_token_hours',Number(values.portalHours)],['high_discount_limit',Number(values.discountLimit)]].map(([key,value])=>({organization_id:context.org,branch_id:context.branch,key,value:{value},created_by:context.user,updated_by:context.user}));const{error:e}=await createClient().from("application_settings").upsert(rows,{onConflict:"organization_id,branch_id,key"});if(e)throw e;setMessage("Configurações salvas e auditadas.")}catch(c){setError(c instanceof Error?c.message:"Não foi possível salvar.")}finally{setSaving(false)}};
 if(loading)return <main className="grid min-h-[60vh] place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></main>;
 return <main className="mx-auto max-w-[900px] px-4 py-5 lg:px-7 lg:py-6"><div className="mb-5"><p className="mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--brand)]">Administração</p><h1 className="text-2xl font-bold">Configurações operacionais</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">Regras aplicadas à filial ativa e registradas na auditoria.</p></div>{error&&<div className="mb-4 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{error}</div>}{message&&<div className="mb-4 border border-[#aad8cf] bg-[var(--brand-soft)] px-4 py-3 text-xs text-[var(--brand)]">{message}</div>}<form onSubmit={submit} className="border border-[var(--line)] bg-[var(--surface)]"><section className="border-b border-[var(--line)] p-5"><h2 className="font-bold">Estoque</h2><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="flex items-start gap-3 border border-[var(--line)] p-4 text-xs"><input type="checkbox" checked={values.allowNegative} onChange={e=>setValues(v=>({...v,allowNegative:e.target.checked}))} className="mt-0.5 size-4"/><span><strong className="block">Permitir estoque negativo</strong><span className="mt-1 block text-[var(--ink-muted)]">Ainda depende da permissão específica do usuário.</span></span></label><label className="text-xs font-bold">Evento de baixa<select className="field mt-2 w-full" value={values.stockEvent} onChange={e=>setValues(v=>({...v,stockEvent:e.target.value}))}><option value="work_order_start">Início da execução</option><option value="work_order_finish">Conclusão do serviço</option><option value="delivery">Entrega do veículo</option></select></label></div></section><section className="grid gap-5 border-b border-[var(--line)] p-5 sm:grid-cols-2"><label className="text-xs font-bold">Garantia padrão (dias)<input type="number" min="0" max="3650" className="field mt-2 w-full" value={values.warrantyDays} onChange={e=>setValues(v=>({...v,warrantyDays:e.target.value}))}/></label><label className="text-xs font-bold">Validade do portal (horas)<input type="number" min="1" max="720" className="field mt-2 w-full" value={values.portalHours} onChange={e=>setValues(v=>({...v,portalHours:e.target.value}))}/></label><label className="text-xs font-bold">Desconto com justificativa a partir de (%)<input type="number" min="0" max="100" step="0.01" className="field mt-2 w-full" value={values.discountLimit} onChange={e=>setValues(v=>({...v,discountLimit:e.target.value}))}/></label></section><div className="flex justify-end p-5"><button disabled={saving} className="inline-flex h-10 items-center gap-2 bg-[var(--brand)] px-5 text-sm font-bold text-white disabled:opacity-60">{saving?<LoaderCircle size={16} className="animate-spin"/>:<Save size={16}/>}Salvar configurações</button></div></form></main>;
}
