"use client";

import { CheckCircle2, LoaderCircle, Plus, RefreshCw, ShieldCheck, Wrench, XCircle } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Warranty={id:string;customer_id:string;vehicle_id:string;work_order_id:string|null;description:string;expires_at:string;status:string};type Claim={id:string;warranty_id:string;customer_id:string;vehicle_id:string;status:string;reason:string;diagnosis:string|null;estimated_cost:number;actual_cost:number;return_work_order_id:string|null;created_at:string};type Context={organizationId:string;branchId:string;userId:string};

export function WarrantyClaims(){
 const[warranties,setWarranties]=useState<Warranty[]>([]);const[claims,setClaims]=useState<Claim[]>([]);const[context,setContext]=useState<Context|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);const[form,setForm]=useState({warranty_id:"",reason:"",diagnosis:"",estimated_cost:"0"});
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");const{data:p}=await s.from("profiles").select("last_organization_id,last_branch_id").eq("id",user.id).single();if(!p?.last_organization_id||!p.last_branch_id)throw new Error("Conclua o onboarding.");setContext({organizationId:p.last_organization_id,branchId:p.last_branch_id,userId:user.id});const[w,c]=await Promise.all([s.from("warranties").select("id,customer_id,vehicle_id,work_order_id,description,expires_at,status").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).in("status",["active","claimed"]).is("deleted_at",null).order("expires_at"),s.from("warranty_claims").select("id,warranty_id,customer_id,vehicle_id,status,reason,diagnosis,estimated_cost,actual_cost,return_work_order_id,created_at").eq("organization_id",p.last_organization_id).eq("branch_id",p.last_branch_id).is("deleted_at",null).order("created_at",{ascending:false})]);if(w.error||c.error)throw w.error??c.error;setWarranties((w.data??[])as Warranty[]);setClaims((c.data??[])as Claim[])}catch(c){setError(c instanceof Error?c.message:"Não foi possível carregar os retornos.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);const warrantyMap=useMemo(()=>Object.fromEntries(warranties.map(w=>[w.id,w])),[warranties]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!context)return;const warranty=warrantyMap[form.warranty_id];if(!warranty)return;setSaving(true);setError(null);const s=createClient();const{error:e2}=await s.from("warranty_claims").insert({organization_id:context.organizationId,branch_id:context.branchId,warranty_id:warranty.id,customer_id:warranty.customer_id,vehicle_id:warranty.vehicle_id,original_work_order_id:warranty.work_order_id,reason:form.reason,diagnosis:form.diagnosis||null,estimated_cost:Number(form.estimated_cost)||0,created_by:context.userId,updated_by:context.userId});if(e2)setError(e2.message);else{setOpen(false);setForm({warranty_id:"",reason:"",diagnosis:"",estimated_cost:"0"});await load()}setSaving(false)};
 const update=async(id:string,status:string)=>{if(!context)return;setSaving(true);setError(null);const s=createClient();const values:Record<string,unknown>={status,updated_by:context.userId};if(status==="completed")values.completed_at=new Date().toISOString();const{error:e}=await s.from("warranty_claims").update(values).eq("id",id);if(e)setError(e.message);else await load();setSaving(false)};
 const decide=async(id:string,approved:boolean)=>{const opinion=window.prompt(approved?"Parecer para aprovação (opcional):":"Motivo da recusa:")??"";if(!approved&&!opinion.trim())return;setSaving(true);setError(null);const s=createClient();const{error:e}=await s.rpc("approve_warranty_claim",{p_claim_id:id,p_approved:approved,p_opinion:opinion||null});if(e)setError(e.message);else await load();setSaving(false)};
 return <main className="mx-auto max-w-[1300px] px-4 py-5 lg:px-7 lg:py-6"><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--brand)]">Garantias</p><h1 className="text-2xl font-bold">Retornos em garantia</h1><p className="mt-1 text-sm text-[var(--ink-muted)]">Registre, analise e aprove retornos sem misturar com a venda original.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="grid size-10 place-items-center border border-[var(--line)]"><RefreshCw size={16}/></button><button onClick={()=>setOpen(true)} className="inline-flex h-10 items-center gap-2 bg-[var(--brand)] px-4 text-sm font-bold text-white"><Plus size={16}/>Nova solicitação</button></div></div>{error&&<div className="mb-4 border border-[#e9b3ad] bg-[#fff3f1] px-4 py-3 text-xs text-[var(--danger)]">{error}</div>}
 <section className="border border-[var(--line)] bg-[var(--surface)]">{loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></div>:claims.length?<div className="divide-y divide-[var(--line)]">{claims.map(c=><article key={c.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_180px_260px] lg:items-center"><div><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-[var(--brand)]"/><p className="font-bold">{warrantyMap[c.warranty_id]?.description??"Garantia"}</p><Status value={c.status}/></div><p className="mt-2 text-sm">{c.reason}</p><p className="mt-1 text-xs text-[var(--ink-muted)]">Solicitado em {date(c.created_at)} • custo previsto {money(c.estimated_cost)}</p></div><div className="text-xs"><p className="text-[var(--ink-muted)]">OS de retorno</p><p className="mt-1 font-bold">{c.return_work_order_id?"Criada e vinculada":"Aguardando aprovação"}</p></div><div className="flex flex-wrap justify-end gap-2">{c.status==="requested"&&<button disabled={saving} onClick={()=>void update(c.id,"analysis")} className="h-9 border border-[var(--line)] px-3 text-xs font-bold">Iniciar análise</button>}{["requested","analysis"].includes(c.status)&&<><button disabled={saving} onClick={()=>void decide(c.id,false)} className="inline-flex h-9 items-center gap-2 border border-[var(--line)] px-3 text-xs font-bold text-[var(--danger)]"><XCircle size={14}/>Recusar</button><button disabled={saving} onClick={()=>void decide(c.id,true)} className="inline-flex h-9 items-center gap-2 bg-[var(--brand)] px-3 text-xs font-bold text-white"><CheckCircle2 size={14}/>Aprovar</button></>}{c.status==="approved"&&<button disabled={saving} onClick={()=>void update(c.id,"in_progress")} className="inline-flex h-9 items-center gap-2 bg-[var(--brand)] px-3 text-xs font-bold text-white"><Wrench size={14}/>Iniciar execução</button>}{c.status==="in_progress"&&<button disabled={saving} onClick={()=>void update(c.id,"completed")} className="inline-flex h-9 items-center gap-2 bg-[var(--brand)] px-3 text-xs font-bold text-white"><CheckCircle2 size={14}/>Concluir</button>}</div></article>)}</div>:<p className="p-10 text-center text-xs text-[var(--ink-muted)]">Nenhum retorno em garantia registrado.</p>}</section>
 {open&&<div className="fixed inset-0 z-50 bg-black/50 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="ml-auto flex h-full max-w-xl flex-col bg-white"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-bold">Nova solicitação de garantia</h2></div><div className="flex-1 space-y-5 overflow-y-auto p-5"><Label text="Garantia"><select required value={form.warranty_id} onChange={e=>setForm({...form,warranty_id:e.target.value})} className="field"><option value="">Selecione</option>{warranties.map(w=><option key={w.id} value={w.id}>{w.description} • até {date(w.expires_at)}</option>)}</select></Label><Label text="Motivo"><textarea required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} className="field h-24 py-2"/></Label><Label text="Diagnóstico inicial"><textarea value={form.diagnosis} onChange={e=>setForm({...form,diagnosis:e.target.value})} className="field h-24 py-2"/></Label><Label text="Custo previsto"><input min="0" step="0.01" type="number" value={form.estimated_cost} onChange={e=>setForm({...form,estimated_cost:e.target.value})} className="field"/></Label></div><div className="flex justify-end gap-2 border-t border-[var(--line)] p-4"><button type="button" onClick={()=>setOpen(false)} className="h-10 border border-[var(--line)] px-4 text-sm font-bold">Cancelar</button><button disabled={saving} className="h-10 bg-[var(--brand)] px-4 text-sm font-bold text-white">Registrar solicitação</button></div></form></div>}</main>;
}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label className="block text-xs font-bold">{text}{children}</label>}function Status({value}:{value:string}){return <span className="rounded-full bg-[var(--brand-soft)] px-2 py-1 text-[10px] font-bold text-[var(--brand)]">{value.replaceAll("_"," ")}</span>}const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);const date=(v:string)=>new Intl.DateTimeFormat("pt-BR").format(new Date(v));
