begin;

-- Phase 5 final security review: the application uses soft deletion and
-- controlled RPCs for operational ledgers. Authenticated clients must never
-- receive physical DELETE privileges directly.
revoke delete on all tables in schema public from authenticated;

-- Identity/bootstrap rows are created by the onboarding RPC. Users may still
-- update their own profile and organization through the existing RLS policies.
revoke insert on table public.profiles from authenticated;
revoke insert on table public.organizations from authenticated;

-- Catalog and sequence metadata are maintained by migrations or SECURITY
-- DEFINER functions, never directly by the browser client.
revoke insert, update on table public.permissions from authenticated;
revoke insert, update on table public.document_sequences from authenticated;

-- Immutable history and audit trails.
revoke insert, update on table public.audit_logs from authenticated;
revoke insert, update on table public.estimate_versions from authenticated;
revoke insert, update on table public.estimate_approvals from authenticated;
revoke insert, update on table public.work_order_status_history from authenticated;
revoke insert, update on table public.vehicle_mileage_history from authenticated;

-- Inventory and purchasing ledgers are posted exclusively through validated
-- RPCs/triggers so balances cannot be forged by a client request.
revoke insert, update on table public.stock_balances from authenticated;
revoke insert, update on table public.stock_movements from authenticated;
revoke insert, update on table public.stock_reservations from authenticated;
revoke insert, update on table public.purchase_receipts from authenticated;
revoke insert, update on table public.purchase_receipt_items from authenticated;

-- Financial ledgers and cash movements are likewise function-only.
revoke insert, update on table public.financial_transactions from authenticated;
revoke insert, update on table public.cash_sessions from authenticated;
revoke insert, update on table public.cash_movements from authenticated;

-- Phase 5 system-generated records.
revoke insert, update on table public.automation_jobs from authenticated;
revoke insert, update on table public.customer_feedback from authenticated;
revoke insert, update on table public.integration_events from authenticated;
revoke insert, update on table public.privacy_requests from authenticated;

-- Notifications are generated by the refresh RPC. The browser can only mark a
-- notification as read; all remaining fields stay immutable.
revoke insert, update on table public.notifications from authenticated;
grant update (read_at) on table public.notifications to authenticated;

-- Portal tokens are created by the secure issue RPC. Revocation is the only
-- direct client-side mutation and is still constrained by RLS.
revoke insert, update on table public.portal_access_tokens from authenticated;
grant update (revoked_at) on table public.portal_access_tokens to authenticated;

commit;
